name: Ember
options:
  bundleIdPrefix: com.datanoise
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.3.0"
    CURRENT_PROJECT_VERSION: "4"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  Ember:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Sources
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.datanoise.ember
        PRODUCT_NAME: Ember
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        SWIFT_VERSION: "5.0"
        SUPPORTS_MACCATALYST: "YES"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: "YES"
        MACOSX_DEPLOYMENT_TARGET: "15.0"
